modLoader="javafml"
loaderVersion="[45,)" # 使用するForgeのバージョン範囲
mod {
    modId="more_sword_mod"
    version="1.0"
    displayName="More Sword Mod"
    description="A mod that adds more swords to the game."
    authors="Your Name"
}
